export const FETCH_DISHES_REQUEST = 'FETCH_DISHES_REQUEST';
export const FETCH_DISHES_SUCCESS = 'FETCH_DISHES_SUCCESS';
export const FETCH_DISHES_ERROR = 'FETCH_DISHES_ERROR';
export const ADD_DISH_TO_FRB = 'ADD_DISH_TO_FRB';
export const DELETE_DISH_FROM_FRB = 'DELETE_DISH_FROM_FRB';
export const CHANGE_DISH_FROM_FRB = 'CHANGE_DISH_FROM_FRB';
export const POST_DISH_TO_FRB_REQUEST = 'POST_DISH_TO_FRB_REQUEST';
export const POST_DISH_TO_FRB_ERROR = 'POST_DISH_TO_FRB_ERROR';
export const VALUE_CHANGE = 'VALUE_CHANGE';
export const DELETE_DISH_FROM_FRB_ERROR = 'DELETE_DISH_FROM_FRB_ERROR';
export const DELETE_DISH_FROM_FRB_REQUEST = 'DELETE_DISH_FROM_FRB_REQUEST';
export const CHANGE_DISH_FROM_FRB_REQUEST = 'CHANGE_DISH_FROM_FRB_REQUEST';
export const CHANGE_DISH_FROM_FRB_ERROR = 'CHANGE_DISH_FROM_FRB_ERROR';


export const ORDERS_SUCCESS = 'ORDERS_SUCCESS';
export const ORDERS_ERROR = 'ORDERS_ERROR';
export const ORDERS_REQUEST = 'ORDERS_REQUEST';
export const DELETE_ORDER_ERROR = 'DELETE_ORDER_ERROR';
export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';